name: Release

on:
  push:
    paths:
      - "app/**"
      - "scripts/**"
      - ".github/workflows/**"
      - "external/payment-sdk/**" # when Payment SDK changes
      - "external/json-utils/**"  # build when something changes in JSON Utils

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: softprops/action-gh-release@v3
